### ISSUE TITLE
no found jar

### ISSUE THREAD

**Issue by u03024218** [cfloersch/RtspClient#1]
groupId>xpertss</groupId>
            <artifactId>sdp</artifactId>
<groupId>xpertss</groupId>
            <artifactId>stdlib</artifactId>

**Comment by cfloersch** [comment]
Yea, sorry, all of the xpertss dependencies are my own. I don't yet publish to a public maven repository. So you'll have to access those projects here on git hub and build them into your local repository before building the rtsp client.

Fortunately, those two projects do not have any dependencies of their own..

**Comment by u03024218** [comment]
I can not Find this Project  in GitHub  . Can you  give me  a  URL Or  a  keyword

**Comment by cfloersch** [comment]
https://github.com/cfloersch?tab=repositories

**Comment by u03024218** [comment]
thank you very much .
